// Pin Name, Port Number, Pin Number, AF, Input ON bit.
OMV_GPIO_DEFINE(LED_R, PORT_0, PIN_0, GPIO, false)
OMV_GPIO_DEFINE(LED_G, PORT_6, PIN_3, GPIO, false)
OMV_GPIO_DEFINE(LED_B, PORT_6, PIN_0, GPIO, false)

OMV_GPIO_DEFINE(I2C0_SDA, PORT_3, PIN_5, I2C0_SDA, true)
OMV_GPIO_DEFINE(I2C0_SCL, PORT_3, PIN_4, I2C0_SCL, true)

OMV_GPIO_DEFINE(I2C1_SDA, PORT_0, PIN_4, I2C1_SDA, true)
OMV_GPIO_DEFINE(I2C1_SCL, PORT_0, PIN_5, I2C1_SCL, true)

OMV_GPIO_DEFINE(I2C2_SDA, PORT_5, PIN_0, I2C2_SDA, true)
OMV_GPIO_DEFINE(I2C2_SCL, PORT_5, PIN_1, I2C2_SCL, true)

OMV_GPIO_DEFINE(I2C3_SDA, PORT_1, PIN_0, I2C3_SDA, true)
OMV_GPIO_DEFINE(I2C3_SCL, PORT_1, PIN_1, I2C3_SCL, true)

OMV_GPIO_DEFINE(I3C_SDA, PORT_1, PIN_2, I3C_SDA, true)
OMV_GPIO_DEFINE(I3C_SCL, PORT_1, PIN_3, I3C_SCL, true)

// MIC
OMV_GPIO_DEFINE(PDM_D1, PORT_3, PIN_7, LPPDM_D1, true)
OMV_GPIO_DEFINE(PDM_C1, PORT_3, PIN_6, LPPDM_C1, false)

OMV_GPIO_DEFINE(USB_SWITCH, PORT_15, PIN_0, GPIO, false)
OMV_GPIO_DEFINE(TOF_POWER, PORT_5, PIN_6, GPIO, false)

OMV_GPIO_DEFINE(CSI_D0, PORT_8, PIN_0, CAM_D0, true)
OMV_GPIO_DEFINE(CSI_D1, PORT_8, PIN_1, CAM_D1, true)
OMV_GPIO_DEFINE(CSI_D2, PORT_8, PIN_2, CAM_D2, true)
OMV_GPIO_DEFINE(CSI_D3, PORT_8, PIN_3, CAM_D3, true)
OMV_GPIO_DEFINE(CSI_D4, PORT_8, PIN_4, CAM_D4, true)
OMV_GPIO_DEFINE(CSI_D5, PORT_8, PIN_5, CAM_D5, true)
OMV_GPIO_DEFINE(CSI_D6, PORT_8, PIN_6, CAM_D6, true)
OMV_GPIO_DEFINE(CSI_D7, PORT_8, PIN_7, CAM_D7, true)
OMV_GPIO_DEFINE(CSI_HSYNC, PORT_10, PIN_0, CAM_HSYNC, true)
OMV_GPIO_DEFINE(CSI_VSYNC, PORT_10, PIN_1, CAM_VSYNC, true)
OMV_GPIO_DEFINE(CSI_PXCLK, PORT_10, PIN_2, CAM_PCLK, true)
OMV_GPIO_DEFINE(CSI_MXCLK, PORT_10, PIN_3, CAM_XVCLK, false)
OMV_GPIO_DEFINE(CSI_POWER, PORT_4, PIN_0, GPIO, false)
OMV_GPIO_DEFINE(CSI_RESET, PORT_4, PIN_1, GPIO, false)

// IMU
OMV_GPIO_DEFINE(LPSPI_MISO, PORT_11, PIN_4, LPSPI_MISO, true)
OMV_GPIO_DEFINE(LPSPI_MOSI, PORT_11, PIN_5, LPSPI_MOSI, true)
OMV_GPIO_DEFINE(LPSPI_SCLK, PORT_11, PIN_6, LPSPI_SCLK, true)
OMV_GPIO_DEFINE(LPSPI_SSEL, PORT_11, PIN_7, LPSPI_SS, true)

OMV_GPIO_DEFINE(BT_REG_ON, PORT_5, PIN_7, GPIO, false)
OMV_GPIO_DEFINE(WL_REG_ON, PORT_10, PIN_4, GPIO, false)
