OMV_GPIO_DEFINE(E, 15, AF5, SPI5)       // SCLK
OMV_GPIO_DEFINE(D, 4,  AF5, SPI5)       // MISO
OMV_GPIO_DEFINE(A, 4,  AF5, SPI5)       // MOSI
OMV_GPIO_DEFINE(A, 3,  AF5, SPI5)       // SSEL

OMV_GPIO_DEFINE(B, 10, AF4, I2C2)       // I2C2_SCL
OMV_GPIO_DEFINE(B, 11, AF4, I2C2)       // I2C2_SDA

OMV_GPIO_DEFINE(A, 8,  AF4, I2C3)       // I2C3_SCL
OMV_GPIO_DEFINE(A, 9,  AF4, I2C3)       // I2C3_SDA

OMV_GPIO_DEFINE(E, 13, AF4, I2C4)       // I2C4_SCL
OMV_GPIO_DEFINE(E, 14, AF4, I2C4)       // I2C4_SDA

OMV_GPIO_DEFINE(E, 2,  AF3, ADF1)       // ADF1_CCK0
OMV_GPIO_DEFINE(B, 2,  AF3, ADF1)       // ADF1_SDI0

OMV_GPIO_DEFINE(A, 1,  AF9, DCMI)       // CSI_D0
OMV_GPIO_DEFINE(A, 10, AF9, DCMI)       // CSI_D1
OMV_GPIO_DEFINE(E, 0,  AF9, DCMI)       // CSI_D2
OMV_GPIO_DEFINE(E, 10, AF9, DCMI)       // CSI_D3
OMV_GPIO_DEFINE(B, 0,  AF9, DCMI)       // CSI_D4
OMV_GPIO_DEFINE(E, 5,  AF9, DCMI)       // CSI_D5
OMV_GPIO_DEFINE(G, 2,  AF9, DCMI)       // CSI_D6
OMV_GPIO_DEFINE(F, 1,  AF9, DCMI)       // CSI_D7
OMV_GPIO_DEFINE(E, 9,  AF1, TIM1)       // CSI_CLK
OMV_GPIO_DEFINE(D, 0,  AF9, DCMI)       // CSI_HSYNC
OMV_GPIO_DEFINE(E, 6,  AF9, DCMI)       // CSI_VSYNC
OMV_GPIO_DEFINE(G, 1,  AF9, DCMI)       // CSI_PXCLK
OMV_GPIO_DEFINE(E, 3,  NONE, GPIO)      // CSI_RESET
OMV_GPIO_DEFINE(E, 1,  NONE, GPIO)      // CSI_POWER

OMV_GPIO_DEFINE(P, 0,  AF9, XSPIM_P1)   // XSPIM_IO0
OMV_GPIO_DEFINE(P, 1,  AF9, XSPIM_P1)   // XSPIM_IO1
OMV_GPIO_DEFINE(P, 2,  AF9, XSPIM_P1)   // XSPIM_IO2
OMV_GPIO_DEFINE(P, 3,  AF9, XSPIM_P1)   // XSPIM_IO3
OMV_GPIO_DEFINE(P, 4,  AF9, XSPIM_P1)   // XSPIM_IO4
OMV_GPIO_DEFINE(P, 5,  AF9, XSPIM_P1)   // XSPIM_IO5
OMV_GPIO_DEFINE(P, 6,  AF9, XSPIM_P1)   // XSPIM_IO6
OMV_GPIO_DEFINE(P, 7,  AF9, XSPIM_P1)   // XSPIM_IO7
OMV_GPIO_DEFINE(P, 8,  AF9, XSPIM_P1)   // XSPIM_IO8
OMV_GPIO_DEFINE(P, 9,  AF9, XSPIM_P1)   // XSPIM_IO9
OMV_GPIO_DEFINE(P, 10, AF9, XSPIM_P1)   // XSPIM_IO10
OMV_GPIO_DEFINE(P, 11, AF9, XSPIM_P1)   // XSPIM_IO11
OMV_GPIO_DEFINE(P, 12, AF9, XSPIM_P1)   // XSPIM_IO12
OMV_GPIO_DEFINE(P, 13, AF9, XSPIM_P1)   // XSPIM_IO13
OMV_GPIO_DEFINE(P, 14, AF9, XSPIM_P1)   // XSPIM_IO14
OMV_GPIO_DEFINE(P, 15, AF9, XSPIM_P1)   // XSPIM_IO15

OMV_GPIO_DEFINE(O, 0,  AF9, XSPIM_P1)   // XSPIM_NCS1
OMV_GPIO_DEFINE(O, 2,  AF9, XSPIM_P1)   // XSPIM_DQS0
OMV_GPIO_DEFINE(O, 3,  AF9, XSPIM_P1)   // XSPIM_DQS1
OMV_GPIO_DEFINE(O, 4,  AF9, XSPIM_P1)   // XSPIM_CLKP
