static const char fresh_readme_txt[] =
    "Thank you for supporting Arduino and the OpenMV project!\r\n"
    "\r\n"
    "To download the OpenMV IDE, please visit:\r\n"
    "https://openmv.io/pages/download\r\n"
    "\r\n"
    "For tutorials and documentation, please visit:\r\n"
    "https://docs.arduino.cc/\r\n"
    "http://docs.openmv.io/\r\n"
    "\r\n"
    "For technical OpenMV support and projects, please visit the forums:\r\n"
    "http://forums.openmv.io/\r\n"
    "\r\n"
    "For Arduino related issues, please visit the Arduino help center:\r\n"
    "https://support.arduino.cc/\r\n"
    "\r\n"
    "Please use Github to report bugs and issues:\r\n"
    "https://github.com/openmv/openmv\r\n"
;
