// THIS FILE IS AUTO-GENERATED DO NOT EDIT.

/*
 * Copyright (C) 2023-2024 OpenMV, LLC.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 * 3. Any redistribution, use, or modification in source or binary form
 *    is done solely for personal benefit and not for any commercial
 *    purpose or for monetary gain. For commercial licensing options,
 *    please contact openmv@openmv.io
 *
 * THIS SOFTWARE IS PROVIDED BY THE LICENSOR AND COPYRIGHT OWNER "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 * THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE LICENSOR OR COPYRIGHT
 * OWNER BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
 * EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
 * PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
 * PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY
 * OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
//  PORT_0_PIN_0
#define PORT_0_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_0_AF_OSPI0_D0       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_0_AF_UART0_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_0_AF_I3C_SDA        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_0_AF_UT0_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_0_AF_LPCAM_HSYNC    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_0_AF_CAM_HSYNC      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_0_PIN_0_AF_ANA_S0         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_1
#define PORT_0_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_1_AF_OSPI0_D1       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_1_AF_UART0_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_1_AF_I3C_SCL        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_1_AF_UT0_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_1_AF_LPCAM_VSYNC    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_1_AF_CAM_VSYNC      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_0_PIN_1_AF_ANA_S1         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_2
#define PORT_0_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_2_AF_OSPI0_D2       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_2_AF_UART0_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_2_AF_I2C0_SDA       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_2_AF_UT1_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_2_AF_LPCAM_PCLK     PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_2_AF_CAM_PCLK       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_0_PIN_2_AF_ANA_S2         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_3
#define PORT_0_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_3_AF_OSPI0_D3       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_3_AF_UART0_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_3_AF_I2C0_SCL       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_3_AF_UT1_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_3_AF_LPCAM_XVCLK    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_3_AF_CAM_XVCLK      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_0_PIN_3_AF_ANA_S3         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_4
#define PORT_0_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_4_AF_OSPI0_D4       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_4_AF_UART1_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_4_AF_PDM_D0         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_4_AF_I2C1_SDA       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_4_AF_UT2_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_4_AF_ANA_S4         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_5
#define PORT_0_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_5_AF_OSPI0_D5       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_5_AF_UART1_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_5_AF_PDM_C0         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_5_AF_I2C1_SCL       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_5_AF_UT2_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_5_AF_ANA_S5         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_6
#define PORT_0_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_6_AF_OSPI0_D6       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_6_AF_UART1_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_6_AF_PDM_D1         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_6_AF_I2C2_SCL       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_6_AF_UT3_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_6_AF_ANA_S6         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_0_PIN_7
#define PORT_0_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_0_PIN_7_AF_OSPI0_D7       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_0_PIN_7_AF_UART1_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_0_PIN_7_AF_PDM_C1         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_0_PIN_7_AF_I2C2_SDA       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_0_PIN_7_AF_UT3_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_0_PIN_7_AF_CDC_DE         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_0_PIN_7_AF_ANA_S7         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_0
#define PORT_1_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_0_AF_UART2_RX       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_0_AF_SPI0_MISO      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_0_AF_I2C3_SDA       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_0_AF_UT4_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_0_AF_LPCAM_HSYNC    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_0_AF_ETH_RXD0       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_0_AF_ANA_S8         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_1
#define PORT_1_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_1_AF_UART2_TX       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_1_AF_SPI0_MOSI      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_1_AF_I2C3_SCL       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_1_AF_UT4_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_1_AF_LPCAM_VSYNC    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_1_AF_ETH_RXD1       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_1_AF_ANA_S9         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_2
#define PORT_1_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_2_AF_UART3_RX       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_2_AF_SPI0_SCLK      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_2_AF_I3C_SDA        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_2_AF_UT5_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_2_AF_LPCAM_PCLK     PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_2_AF_ETH_RST        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_2_AF_ANA_S10        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_3
#define PORT_1_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_3_AF_UART3_TX       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_3_AF_SPI0_SS0       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_3_AF_I3C_SCL        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_3_AF_UT5_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_3_AF_LPCAM_XVCLK    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_3_AF_ETH_TXD0       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_3_AF_ANA_S11        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_4
#define PORT_1_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_4_AF_OSPI0_SS0      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_4_AF_UART0_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_4_AF_SPI0_SS1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_4_AF_UT6_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_4_AF_LPCAM_D0       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_4_AF_ETH_TXD1       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_4_AF_ANA_S12        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_5
#define PORT_1_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_5_AF_OSPI0_SS1      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_5_AF_UART0_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_5_AF_SPI0_SS2       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_5_AF_UT6_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_5_AF_LPCAM_D1       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_5_AF_ETH_TXEN       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_5_AF_ANA_S13        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_6
#define PORT_1_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_6_AF_OSPI0_RXDS     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_6_AF_UART1_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_6_AF_I2S0_SDI       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_6_AF_UT7_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_6_AF_LPCAM_D2       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_6_AF_ETH_IRQ        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_6_AF_ANA_S14        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_1_PIN_7
#define PORT_1_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_1_PIN_7_AF_OSPI0_SCLK     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_1_PIN_7_AF_UART1_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_1_PIN_7_AF_I2S0_SDO       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_1_PIN_7_AF_UT7_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_1_PIN_7_AF_LPCAM_D3       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_1_PIN_7_AF_ETH_REFCLK     PINMUX_ALTERNATE_FUNCTION_6
#define PORT_1_PIN_7_AF_ANA_S15        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_0
#define PORT_2_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_0_AF_OSPI0_D0       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_0_AF_UART2_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_0_AF_LPPDM_D0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_0_AF_UT8_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_0_AF_LPCAM_D4       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_0_AF_ETH_MDIO       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_0_AF_ANA_S16        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_1
#define PORT_2_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_1_AF_OSPI0_D1       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_1_AF_UART2_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_1_AF_LPPDM_C0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_1_AF_UT8_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_1_AF_LPCAM_D5       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_1_AF_ETH_MDC        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_1_AF_ANA_S17        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_2
#define PORT_2_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_2_AF_OSPI0_D2       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_2_AF_UART3_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_2_AF_LPPDM_D1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_2_AF_UT9_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_2_AF_LPCAM_D6       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_2_AF_ETH_CRS_DV_C   PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_2_AF_ANA_S18        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_3
#define PORT_2_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_3_AF_OSPI0_D3       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_3_AF_UART3_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_3_AF_LPPDM_C1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_3_AF_UT9_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_3_AF_LPCAM_D7       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_3_AF_CDC_PCLK       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_3_AF_ANA_S19        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_4
#define PORT_2_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_4_AF_OSPI0_D4       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_4_AF_LPI2S_SDI      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_4_AF_SPI1_MISO      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_4_AF_UT10_T0        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_4_AF_LPCAM_D0       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_4_AF_CAM_D0         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_4_AF_ANA_S20        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_5
#define PORT_2_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_5_AF_OSPI0_D5       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_5_AF_LPI2S_SDO      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_5_AF_SPI1_MOSI      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_5_AF_UT10_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_5_AF_LPCAM_D1       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_5_AF_CAM_D1         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_5_AF_ANA_S21        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_6
#define PORT_2_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_6_AF_OSPI0_D6       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_6_AF_LPI2S_SCLK     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_6_AF_SPI1_SCLK      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_6_AF_UT11_T0        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_6_AF_LPCAM_D2       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_6_AF_CAM_D2         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_6_AF_ANA_S22        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_2_PIN_7
#define PORT_2_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_2_PIN_7_AF_OSPI0_D7       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_2_PIN_7_AF_LPI2S_WS       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_2_PIN_7_AF_SPI1_SS0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_2_PIN_7_AF_UT11_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_2_PIN_7_AF_LPCAM_D3       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_2_PIN_7_AF_CAM_D3         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_2_PIN_7_AF_ANA_S23        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_0
#define PORT_3_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_0_AF_OSPI0_SCLK     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_0_AF_UART4_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_0_AF_PDM_D0         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_0_AF_I2S0_SCLK      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_0_AF_QEC0_X         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_0_AF_LPCAM_D4       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_0_AF_CAM_D4         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_1
#define PORT_3_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_1_AF_OSPI0_SCLKN    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_1_AF_UART4_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_1_AF_PDM_C0         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_1_AF_I2S0_WS        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_1_AF_QEC0_Y         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_1_AF_LPCAM_D5       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_1_AF_CAM_D5         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_2
#define PORT_3_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_2_AF_OSPI0_SS0      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_2_AF_PDM_D1         PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_2_AF_I2S1_SDI       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_2_AF_I3C_SDA        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_2_AF_QEC0_Z         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_2_AF_LPCAM_D6       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_2_AF_CAM_D6         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_3
#define PORT_3_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_3_AF_OSPI0_SS1      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_3_AF_PDM_C1         PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_3_AF_I2S1_SDO       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_3_AF_I3C_SCL        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_3_AF_QEC1_X         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_3_AF_LPCAM_D7       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_3_AF_CAM_D7         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_4
#define PORT_3_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_4_AF_OSPI0_RXDS     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_4_AF_UART5_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_4_AF_LPPDM_C0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_4_AF_I2S1_SCLK      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_4_AF_I2C0_SCL       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_4_AF_QEC1_Y         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_4_AF_CAM_D8         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_5
#define PORT_3_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_5_AF_OSPI0_SCLKN    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_5_AF_UART5_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_5_AF_LPPDM_D0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_5_AF_SPI0_SS1       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_5_AF_I2C0_SDA       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_5_AF_QEC1_Z         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_5_AF_CAM_D9         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_6
#define PORT_3_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_6_AF_HFXO_OUT       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_6_AF_LPUART_CTS     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_6_AF_LPPDM_C1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_6_AF_SPI0_SS2       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_6_AF_I2C1_SDA       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_6_AF_QEC2_X         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_6_AF_CAM_D10        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_3_PIN_7
#define PORT_3_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_3_PIN_7_AF_JTAG_TRACECLK  PINMUX_ALTERNATE_FUNCTION_1
#define PORT_3_PIN_7_AF_LPUART_RTS     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_3_PIN_7_AF_LPPDM_D1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_3_PIN_7_AF_SPI1_SS1       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_3_PIN_7_AF_I2C1_SCL       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_3_PIN_7_AF_QEC2_Y         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_3_PIN_7_AF_CAM_D11        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_4_PIN_0
#define PORT_4_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_0_AF_JTAG_TDATA0    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_0_AF_I2S1_WS        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_4_PIN_0_AF_SPI1_SS2       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_4_PIN_0_AF_QEC2_Z         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_4_PIN_0_AF_CDC_VSYNC      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_4_PIN_0_AF_CAM_D12        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_4_PIN_1
#define PORT_4_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_1_AF_JTAG_TDATA1    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_1_AF_I2S0_SDI       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_4_PIN_1_AF_SPI1_SS3       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_4_PIN_1_AF_QEC3_X         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_4_PIN_1_AF_SD_CLK         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_4_PIN_1_AF_CDC_HSYNC      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_4_PIN_1_AF_CAM_D13        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_4_PIN_2
#define PORT_4_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_2_AF_JTAG_TDATA2    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_2_AF_I2S0_SDO       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_4_PIN_2_AF_SPI2_MISO      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_4_PIN_2_AF_QEC3_Y         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_4_PIN_2_AF_SD_CMD         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_4_PIN_2_AF_CAM_D14        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_4_PIN_3
#define PORT_4_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_3_AF_JTAG_TDATA3    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_3_AF_I2S0_SCLK      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_4_PIN_3_AF_SPI2_MOSI      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_4_PIN_3_AF_QEC3_Z         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_4_PIN_3_AF_SD_RST         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_4_PIN_3_AF_CAM_D15        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_4_PIN_4
#define PORT_4_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_4_AF_JTAG_TCK       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_4_AF_I2S0_WS        PINMUX_ALTERNATE_FUNCTION_2
#define PORT_4_PIN_4_AF_SPI2_SCLK      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_4_PIN_4_AF_FAULT0_A       PINMUX_ALTERNATE_FUNCTION_4

//  PORT_4_PIN_5
#define PORT_4_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_5_AF_JTAG_TMS       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_5_AF_SPI2_SS0       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_4_PIN_5_AF_FAULT1_A       PINMUX_ALTERNATE_FUNCTION_3

//  PORT_4_PIN_6
#define PORT_4_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_6_AF_JTAG_TDI       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_6_AF_SPI2_SS1       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_4_PIN_6_AF_FAULT2_A       PINMUX_ALTERNATE_FUNCTION_3

//  PORT_4_PIN_7
#define PORT_4_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_4_PIN_7_AF_JTAG_TDO       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_4_PIN_7_AF_SPI2_SS2       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_4_PIN_7_AF_FAULT3_A       PINMUX_ALTERNATE_FUNCTION_3

//  PORT_5_PIN_0
#define PORT_5_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_0_AF_OSPI1_RXDS     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_0_AF_UART4_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_0_AF_PDM_D2         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_0_AF_SPI0_MISO      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_0_AF_I2C2_SDA       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_0_AF_UT0_T0         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_0_AF_SD_D0          PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_1
#define PORT_5_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_1_AF_OSPI1_SS0      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_1_AF_UART4_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_1_AF_PDM_D3         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_1_AF_SPI0_MOSI      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_1_AF_I2C2_SCL       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_1_AF_UT0_T1         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_1_AF_SD_D1          PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_2
#define PORT_5_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_2_AF_OSPI1_SCLKN    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_2_AF_UART5_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_2_AF_PDM_C3         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_2_AF_SPI0_SS0       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_2_AF_LPI2C_SCL      PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_2_AF_UT1_T0         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_2_AF_SD_D2          PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_3
#define PORT_5_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_3_AF_OSPI1_SCLK     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_3_AF_UART5_TX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_3_AF_SPI0_SCLK      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_3_AF_LPI2C_SDA      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_3_AF_UT1_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_3_AF_SD_D3          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_3_AF_CDC_PCLK       PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_4
#define PORT_5_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_4_AF_OSPI1_SS1      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_4_AF_UART3_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_4_AF_PDM_D2         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_4_AF_SPI0_SS3       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_4_AF_UT2_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_4_AF_SD_D4          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_4_AF_CDC_DE         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_5
#define PORT_5_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_5_AF_OSPI1_SCLK     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_5_AF_UART3_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_5_AF_PDM_D3         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_5_AF_UT2_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_5_AF_SD_D5          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_5_AF_ETH_RXD0       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_5_AF_CDC_HSYNC      PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_6
#define PORT_5_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_6_AF_UART1_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_6_AF_I2C2_SCL       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_6_AF_UT3_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_6_AF_SD_D6          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_6_AF_ETH_RXD1       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_5_PIN_6_AF_CDC_VSYNC      PINMUX_ALTERNATE_FUNCTION_7

//  PORT_5_PIN_7
#define PORT_5_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_5_PIN_7_AF_OSPI1_SS0      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_5_PIN_7_AF_UART1_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_5_PIN_7_AF_I2C2_SDA       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_5_PIN_7_AF_UT3_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_5_PIN_7_AF_SD_D7          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_5_PIN_7_AF_ETH_RST        PINMUX_ALTERNATE_FUNCTION_6

//  PORT_6_PIN_0
#define PORT_6_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_0_AF_OSPI0_D0       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_0_AF_UART4_DE       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_0_AF_PDM_D0         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_6_PIN_0_AF_UT4_T0         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_0_AF_SD_D0          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_0_AF_ETH_TXD0       PINMUX_ALTERNATE_FUNCTION_6

//  PORT_6_PIN_1
#define PORT_6_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_1_AF_OSPI0_D1       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_1_AF_UART5_DE       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_1_AF_PDM_C0         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_6_PIN_1_AF_UT4_T1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_1_AF_SD_D1          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_1_AF_ETH_TXD1       PINMUX_ALTERNATE_FUNCTION_6

//  PORT_6_PIN_2
#define PORT_6_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_2_AF_OSPI0_D2       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_2_AF_UART2_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_2_AF_PDM_D1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_2_AF_UT5_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_2_AF_SD_D2          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_6_PIN_2_AF_ETH_TXEN       PINMUX_ALTERNATE_FUNCTION_7

//  PORT_6_PIN_3
#define PORT_6_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_3_AF_OSPI0_D3       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_3_AF_UART2_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_3_AF_PDM_C1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_3_AF_UT5_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_3_AF_SD_D3          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_6_PIN_3_AF_ETH_IRQ        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_6_PIN_4
#define PORT_6_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_4_AF_OSPI0_D4       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_4_AF_UART2_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_4_AF_SPI1_SS0       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_4_AF_UT6_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_4_AF_SD_D4          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_6_PIN_4_AF_ETH_REFCLK     PINMUX_ALTERNATE_FUNCTION_7

//  PORT_6_PIN_5
#define PORT_6_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_5_AF_OSPI0_D5       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_5_AF_UART2_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_5_AF_SPI1_SS1       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_5_AF_UT6_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_5_AF_SD_D5          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_6_PIN_5_AF_ETH_MDIO       PINMUX_ALTERNATE_FUNCTION_7

//  PORT_6_PIN_6
#define PORT_6_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_6_AF_OSPI0_D6       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_6_AF_UART0_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_6_AF_SPI1_SS2       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_6_AF_UT7_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_6_AF_SD_D6          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_6_PIN_6_AF_ETH_MDC        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_6_PIN_7
#define PORT_6_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_6_PIN_7_AF_OSPI0_D7       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_6_PIN_7_AF_UART0_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_6_PIN_7_AF_PDM_C2         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_6_PIN_7_AF_SPI1_SS3       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_6_PIN_7_AF_UT7_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_6_PIN_7_AF_SD_D7          PINMUX_ALTERNATE_FUNCTION_6
#define PORT_6_PIN_7_AF_ETH_CRS_DV_A   PINMUX_ALTERNATE_FUNCTION_7

//  PORT_7_PIN_0
#define PORT_7_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_0_AF_CMP3_OUT       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_0_AF_SPI0_MISO      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_7_PIN_0_AF_I2C0_SDA       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_0_AF_UT8_T0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_0_AF_SD_CMD         PINMUX_ALTERNATE_FUNCTION_6

//  PORT_7_PIN_1
#define PORT_7_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_1_AF_CMP2_OUT       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_1_AF_SPI0_MOSI      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_7_PIN_1_AF_I2C0_SCL       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_1_AF_UT8_T1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_1_AF_SD_CLK         PINMUX_ALTERNATE_FUNCTION_6

//  PORT_7_PIN_2
#define PORT_7_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_2_AF_UART3_CTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_2_AF_CMP1_OUT       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_7_PIN_2_AF_SPI0_SCLK      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_2_AF_I2C1_SDA       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_2_AF_UT9_T0         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_7_PIN_2_AF_SD_RST         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_7_PIN_3
#define PORT_7_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_3_AF_UART3_RTS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_3_AF_CMP0_OUT       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_7_PIN_3_AF_SPI0_SS0       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_3_AF_I2C1_SCL       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_3_AF_UT9_T1         PINMUX_ALTERNATE_FUNCTION_6

//  PORT_7_PIN_4
#define PORT_7_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_4_AF_LPUART_CTS     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_4_AF_LPPDM_C2       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_7_PIN_4_AF_LPSPI_MISO     PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_4_AF_LPI2C_SCL      PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_4_AF_UT10_T0        PINMUX_ALTERNATE_FUNCTION_6

//  PORT_7_PIN_5
#define PORT_7_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_5_AF_LPUART_RTS     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_5_AF_LPPDM_D2       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_5_AF_LPSPI_MOSI     PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_5_AF_LPI2C_SDA      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_7_PIN_5_AF_UT10_T1        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_7_PIN_6
#define PORT_7_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_6_AF_LPUART_RX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_6_AF_LPPDM_C3       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_6_AF_LPSPI_SCLK     PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_6_AF_I3C_SDA        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_7_PIN_6_AF_UT11_T0        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_7_PIN_7
#define PORT_7_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_7_PIN_7_AF_LPUART_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_7_PIN_7_AF_LPPDM_D3       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_7_PIN_7_AF_LPSPI_SS       PINMUX_ALTERNATE_FUNCTION_5
#define PORT_7_PIN_7_AF_I3C_SCL        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_7_PIN_7_AF_UT11_T1        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_0
#define PORT_8_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_0_AF_OSPI1_SCLKN    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_8_PIN_0_AF_AUDIO_CLK      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_0_AF_FAULT0_B       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_0_AF_LPCAM_D0       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_0_AF_SD_D0          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_0_AF_CDC_D0         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_0_AF_CAM_D0         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_1
#define PORT_8_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_1_AF_I2S2_SDI       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_8_PIN_1_AF_FAULT1_B       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_1_AF_LPCAM_D1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_1_AF_SD_D1          PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_1_AF_CDC_D1         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_1_AF_CAM_D1         PINMUX_ALTERNATE_FUNCTION_6

//  PORT_8_PIN_2
#define PORT_8_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_2_AF_I2S2_SDO       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_8_PIN_2_AF_SPI0_SS3       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_2_AF_FAULT2_B       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_2_AF_LPCAM_D2       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_2_AF_SD_D2          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_2_AF_CDC_D2         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_2_AF_CAM_D2         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_3
#define PORT_8_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_3_AF_I2S2_SCLK      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_8_PIN_3_AF_SPI1_MISO      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_3_AF_FAULT3_B       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_3_AF_LPCAM_D3       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_3_AF_SD_D3          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_3_AF_CDC_D3         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_3_AF_CAM_D3         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_4
#define PORT_8_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_4_AF_I2S2_WS        PINMUX_ALTERNATE_FUNCTION_1
#define PORT_8_PIN_4_AF_SPI1_MOSI      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_4_AF_QEC0_X         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_4_AF_LPCAM_D4       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_4_AF_SD_D4          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_4_AF_CDC_D4         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_4_AF_CAM_D4         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_5
#define PORT_8_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_5_AF_SPI1_SCLK      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_5_AF_QEC0_Y         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_5_AF_LPCAM_D5       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_5_AF_SD_D5          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_5_AF_CDC_D5         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_5_AF_CAM_D5         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_6
#define PORT_8_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_6_AF_I2S3_SCLK      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_6_AF_QEC0_Z         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_6_AF_LPCAM_D6       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_6_AF_SD_D6          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_6_AF_CDC_D6         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_6_AF_CAM_D6         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_8_PIN_7
#define PORT_8_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_8_PIN_7_AF_I2S3_WS        PINMUX_ALTERNATE_FUNCTION_2
#define PORT_8_PIN_7_AF_QEC1_X         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_8_PIN_7_AF_LPCAM_D7       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_8_PIN_7_AF_SD_D7          PINMUX_ALTERNATE_FUNCTION_5
#define PORT_8_PIN_7_AF_CDC_D7         PINMUX_ALTERNATE_FUNCTION_6
#define PORT_8_PIN_7_AF_CAM_D7         PINMUX_ALTERNATE_FUNCTION_7

//  PORT_9_PIN_0
#define PORT_9_PIN_0_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_0_AF_I2S3_SDI       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_0_AF_QEC1_Y         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_0_AF_SD_CMD         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_0_AF_CDC_D8         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_0_AF_CAM_D8         PINMUX_ALTERNATE_FUNCTION_6

//  PORT_9_PIN_1
#define PORT_9_PIN_1_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_1_AF_LPUART_RX      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_1_AF_I2S3_SDO       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_1_AF_QEC1_Z         PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_1_AF_SD_CLK         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_1_AF_CDC_D9         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_1_AF_CAM_D9         PINMUX_ALTERNATE_FUNCTION_6

//  PORT_9_PIN_2
#define PORT_9_PIN_2_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_2_AF_LPUART_TX      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_2_AF_I2S3_SDI       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_2_AF_SPI2_MISO      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_2_AF_QEC2_X         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_2_AF_SD_RST         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_2_AF_CDC_D10        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_9_PIN_2_AF_CAM_D10        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_9_PIN_3
#define PORT_9_PIN_3_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_3_AF_HFXO_OUT       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_3_AF_UART7_RX       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_3_AF_I2S3_SDO       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_3_AF_SPI2_MOSI      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_3_AF_QEC2_Y         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_3_AF_CDC_D11        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_9_PIN_3_AF_CAM_D11        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_9_PIN_4
#define PORT_9_PIN_4_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_4_AF_UART7_TX       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_4_AF_I2S3_SCLK      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_4_AF_SPI2_SCLK      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_4_AF_I2C3_SDA       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_4_AF_QEC2_Z         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_4_AF_CDC_D12        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_9_PIN_4_AF_CAM_D12        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_9_PIN_5
#define PORT_9_PIN_5_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_5_AF_OSPI1_D0       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_5_AF_I2S3_WS        PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_5_AF_SPI2_SS0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_5_AF_I2C3_SCL       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_5_AF_QEC3_X         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_5_AF_CDC_D13        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_9_PIN_5_AF_CAM_D13        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_9_PIN_6
#define PORT_9_PIN_6_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_6_AF_OSPI1_D1       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_6_AF_AUDIO_CLK      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_6_AF_SPI2_SS1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_6_AF_I2C3_SDA       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_6_AF_QEC3_Y         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_6_AF_CDC_D14        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_9_PIN_6_AF_CAM_D14        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_9_PIN_7
#define PORT_9_PIN_7_AF_GPIO           PINMUX_ALTERNATE_FUNCTION_0
#define PORT_9_PIN_7_AF_OSPI1_D2       PINMUX_ALTERNATE_FUNCTION_1
#define PORT_9_PIN_7_AF_UART7_DE       PINMUX_ALTERNATE_FUNCTION_2
#define PORT_9_PIN_7_AF_SPI2_SS2       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_9_PIN_7_AF_I2C3_SCL       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_9_PIN_7_AF_QEC3_Z         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_9_PIN_7_AF_CDC_D15        PINMUX_ALTERNATE_FUNCTION_6
#define PORT_9_PIN_7_AF_CAM_D15        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_0
#define PORT_10_PIN_0_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_0_AF_OSPI1_D3      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_0_AF_UART6_DE      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_10_PIN_0_AF_SPI2_SS3      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_0_AF_UT0_T0        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_0_AF_LPCAM_HSYNC   PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_0_AF_CDC_D16       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_0_AF_CAM_HSYNC     PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_1
#define PORT_10_PIN_1_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_1_AF_OSPI1_D4      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_1_AF_LPI2S_SDI     PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_1_AF_UT0_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_1_AF_LPCAM_VSYNC   PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_1_AF_CDC_D17       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_1_AF_CAM_VSYNC     PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_2
#define PORT_10_PIN_2_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_2_AF_OSPI1_D5      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_2_AF_LPI2S_SDO     PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_2_AF_UT1_T0        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_2_AF_LPCAM_PCLK    PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_2_AF_CDC_D18       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_2_AF_CAM_PCLK      PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_3
#define PORT_10_PIN_3_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_3_AF_OSPI1_D6      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_3_AF_LPI2S_SCLK    PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_3_AF_UT1_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_3_AF_LPCAM_XVCLK   PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_3_AF_CDC_D19       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_3_AF_CAM_XVCLK     PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_4
#define PORT_10_PIN_4_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_4_AF_OSPI1_D7      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_4_AF_LPI2S_WS      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_4_AF_I2C0_SDA      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_4_AF_UT2_T0        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_4_AF_ETH_TXD0      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_4_AF_CDC_D20       PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_5
#define PORT_10_PIN_5_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_5_AF_UART6_RX      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_5_AF_I2S2_SDI      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_10_PIN_5_AF_SPI3_MISO     PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_5_AF_I2C0_SCL      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_5_AF_UT2_T1        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_5_AF_ETH_TXD1      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_5_AF_CDC_D21       PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_6
#define PORT_10_PIN_6_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_6_AF_UART6_TX      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_6_AF_I2S2_SDO      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_10_PIN_6_AF_SPI3_MOSI     PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_6_AF_I2C1_SDA      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_6_AF_UT3_T0        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_6_AF_ETH_TXEN      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_6_AF_CDC_D22       PINMUX_ALTERNATE_FUNCTION_7

//  PORT_10_PIN_7
#define PORT_10_PIN_7_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_10_PIN_7_AF_UART7_RX      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_10_PIN_7_AF_I2S2_SCLK     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_10_PIN_7_AF_SPI3_SCLK     PINMUX_ALTERNATE_FUNCTION_3
#define PORT_10_PIN_7_AF_I2C1_SCL      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_10_PIN_7_AF_UT3_T1        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_10_PIN_7_AF_CDC_D23       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_10_PIN_7_AF_OSPI1_RXDS    PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_0
#define PORT_11_PIN_0_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_0_AF_OSPI1_D0      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_0_AF_UART7_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_0_AF_I2S2_WS       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_0_AF_SPI3_SS0      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_0_AF_UT4_T0        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_0_AF_ETH_REFCLK    PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_0_AF_CDC_D0        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_1
#define PORT_11_PIN_1_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_1_AF_OSPI1_D1      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_1_AF_UART7_DE      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_1_AF_SPI3_SS1      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_1_AF_UT4_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_1_AF_ETH_MDIO      PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_1_AF_CDC_D1        PINMUX_ALTERNATE_FUNCTION_6

//  PORT_11_PIN_2
#define PORT_11_PIN_2_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_2_AF_OSPI1_D2      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_2_AF_UART6_DE      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_2_AF_LPPDM_C2      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_2_AF_SPI3_SS2      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_2_AF_UT5_T0        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_2_AF_ETH_MDC       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_2_AF_CDC_D2        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_3
#define PORT_11_PIN_3_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_3_AF_OSPI1_D3      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_3_AF_UART5_RX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_3_AF_LPPDM_C3      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_3_AF_SPI3_SS3      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_3_AF_UT5_T1        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_3_AF_ETH_RXD0      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_3_AF_CDC_D3        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_4
#define PORT_11_PIN_4_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_4_AF_OSPI1_D4      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_4_AF_UART5_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_4_AF_PDM_C2        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_4_AF_LPSPI_MISO    PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_4_AF_UT6_T0        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_4_AF_ETH_RXD1      PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_4_AF_CDC_D4        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_5
#define PORT_11_PIN_5_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_5_AF_OSPI1_D5      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_5_AF_UART6_RX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_5_AF_PDM_C3        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_5_AF_LPSPI_MOSI    PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_5_AF_UT6_T1        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_5_AF_ETH_CRS_DV_B  PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_5_AF_CDC_D5        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_6
#define PORT_11_PIN_6_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_6_AF_OSPI1_D6      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_6_AF_UART6_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_6_AF_LPPDM_D2      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_6_AF_LPSPI_SCLK    PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_6_AF_UT7_T0        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_6_AF_ETH_RST       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_6_AF_CDC_D6        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_11_PIN_7
#define PORT_11_PIN_7_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_11_PIN_7_AF_OSPI1_D7      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_11_PIN_7_AF_UART5_DE      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_11_PIN_7_AF_LPPDM_D3      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_11_PIN_7_AF_LPSPI_SS      PINMUX_ALTERNATE_FUNCTION_4
#define PORT_11_PIN_7_AF_UT7_T1        PINMUX_ALTERNATE_FUNCTION_5
#define PORT_11_PIN_7_AF_ETH_IRQ       PINMUX_ALTERNATE_FUNCTION_6
#define PORT_11_PIN_7_AF_CDC_D7        PINMUX_ALTERNATE_FUNCTION_7

//  PORT_12_PIN_0
#define PORT_12_PIN_0_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_0_AF_OSPI0_SCLK    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_12_PIN_0_AF_AUDIO_CLK     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_0_AF_I2S1_SDI      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_0_AF_UT8_T0        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_12_PIN_0_AF_CDC_D8        PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_1
#define PORT_12_PIN_1_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_1_AF_OSPI0_SCLKN   PINMUX_ALTERNATE_FUNCTION_1
#define PORT_12_PIN_1_AF_UART4_RX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_1_AF_I2S1_SDO      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_1_AF_UT8_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_12_PIN_1_AF_CDC_D9        PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_2
#define PORT_12_PIN_2_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_2_AF_OSPI0_RXDS    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_12_PIN_2_AF_UART4_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_2_AF_I2S1_SCLK     PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_2_AF_UT9_T0        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_12_PIN_2_AF_CDC_D10       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_3
#define PORT_12_PIN_3_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_3_AF_OSPI0_SS0     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_12_PIN_3_AF_UART4_DE      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_3_AF_I2S1_WS       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_3_AF_UT9_T1        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_12_PIN_3_AF_CDC_D11       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_4
#define PORT_12_PIN_4_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_4_AF_OSPI0_SS1     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_12_PIN_4_AF_SPI3_MISO     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_4_AF_UT10_T0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_4_AF_CDC_D12       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_5
#define PORT_12_PIN_5_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_5_AF_SPI3_MOSI     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_5_AF_UT10_T1       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_5_AF_CDC_D13       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_6
#define PORT_12_PIN_6_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_6_AF_SPI3_SCLK     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_12_PIN_6_AF_UT11_T0       PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_6_AF_CDC_D14       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_12_PIN_7
#define PORT_12_PIN_7_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_12_PIN_7_AF_OSPI1_RXDS    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_12_PIN_7_AF_SPI3_SS0      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_12_PIN_7_AF_UT11_T1       PINMUX_ALTERNATE_FUNCTION_4
#define PORT_12_PIN_7_AF_CDC_D15       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_0
#define PORT_13_PIN_0_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_0_AF_OSPI1_D0      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_0_AF_SPI3_SS1      PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_0_AF_QEC0_X        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_0_AF_SD_D0         PINMUX_ALTERNATE_FUNCTION_5
#define PORT_13_PIN_0_AF_CDC_D16       PINMUX_ALTERNATE_FUNCTION_6

//  PORT_13_PIN_1
#define PORT_13_PIN_1_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_1_AF_OSPI1_D1      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_1_AF_SPI3_SS2      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_1_AF_QEC0_Y        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_1_AF_SD_D1         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_1_AF_CDC_D17       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_2
#define PORT_13_PIN_2_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_2_AF_OSPI1_D2      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_2_AF_SPI3_SS3      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_2_AF_QEC0_Z        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_2_AF_SD_D2         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_2_AF_CDC_D18       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_3
#define PORT_13_PIN_3_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_3_AF_OSPI1_D3      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_3_AF_SPI2_SS3      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_3_AF_QEC1_X        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_3_AF_SD_D3         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_3_AF_CDC_D19       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_4
#define PORT_13_PIN_4_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_4_AF_OSPI1_D4      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_4_AF_LPI2S_SDI     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_4_AF_QEC1_Y        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_4_AF_SD_D4         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_4_AF_CDC_D20       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_5
#define PORT_13_PIN_5_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_5_AF_OSPI1_D5      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_5_AF_LPI2S_SDO     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_5_AF_QEC1_Z        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_5_AF_SD_D5         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_5_AF_CDC_D21       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_6
#define PORT_13_PIN_6_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_6_AF_OSPI1_D6      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_6_AF_LPI2S_SCLK    PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_6_AF_QEC2_X        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_6_AF_SD_D6         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_6_AF_CDC_D22       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_13_PIN_7
#define PORT_13_PIN_7_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_13_PIN_7_AF_OSPI1_D7      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_13_PIN_7_AF_LPI2S_WS      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_13_PIN_7_AF_QEC2_Y        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_13_PIN_7_AF_SD_D7         PINMUX_ALTERNATE_FUNCTION_4
#define PORT_13_PIN_7_AF_CDC_D23       PINMUX_ALTERNATE_FUNCTION_5

//  PORT_14_PIN_0
#define PORT_14_PIN_0_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_0_AF_OSPI1_SCLK    PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_0_AF_UART6_RX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_0_AF_QEC2_Z        PINMUX_ALTERNATE_FUNCTION_3
#define PORT_14_PIN_0_AF_SD_CMD        PINMUX_ALTERNATE_FUNCTION_4

//  PORT_14_PIN_1
#define PORT_14_PIN_1_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_1_AF_OSPI1_SCLKN   PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_1_AF_UART6_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_1_AF_QEC3_X        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_14_PIN_1_AF_SD_CLK        PINMUX_ALTERNATE_FUNCTION_5

//  PORT_14_PIN_2
#define PORT_14_PIN_2_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_2_AF_OSPI1_SS0     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_2_AF_UART7_RX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_2_AF_QEC3_Y        PINMUX_ALTERNATE_FUNCTION_4
#define PORT_14_PIN_2_AF_SD_RST        PINMUX_ALTERNATE_FUNCTION_5

//  PORT_14_PIN_3
#define PORT_14_PIN_3_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_3_AF_OSPI1_SS1     PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_3_AF_UART7_TX      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_3_AF_QEC3_Z        PINMUX_ALTERNATE_FUNCTION_4

//  PORT_14_PIN_4
#define PORT_14_PIN_4_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_4_AF_CMP3_OUT      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_4_AF_SPI1_MISO     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_4_AF_FAULT0_C      PINMUX_ALTERNATE_FUNCTION_3

//  PORT_14_PIN_5
#define PORT_14_PIN_5_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_5_AF_CMP2_OUT      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_5_AF_SPI1_MOSI     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_5_AF_FAULT1_C      PINMUX_ALTERNATE_FUNCTION_3

//  PORT_14_PIN_6
#define PORT_14_PIN_6_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_6_AF_CMP1_OUT      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_6_AF_SPI1_SCLK     PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_6_AF_FAULT2_C      PINMUX_ALTERNATE_FUNCTION_3

//  PORT_14_PIN_7
#define PORT_14_PIN_7_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_14_PIN_7_AF_CMP0_OUT      PINMUX_ALTERNATE_FUNCTION_1
#define PORT_14_PIN_7_AF_SPI1_SS0      PINMUX_ALTERNATE_FUNCTION_2
#define PORT_14_PIN_7_AF_FAULT3_C      PINMUX_ALTERNATE_FUNCTION_3

//  PORT_15_PIN_0
#define PORT_15_PIN_0_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_15_PIN_0_AF_LPTMR0_CLK    PINMUX_ALTERNATE_FUNCTION_1

//  PORT_15_PIN_1
#define PORT_15_PIN_1_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_15_PIN_1_AF_LPTMR1_CLK    PINMUX_ALTERNATE_FUNCTION_1

//  PORT_15_PIN_2
#define PORT_15_PIN_2_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_15_PIN_2_AF_LPTMR2_CLK    PINMUX_ALTERNATE_FUNCTION_1

//  PORT_15_PIN_3
#define PORT_15_PIN_3_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0
#define PORT_15_PIN_3_AF_LPTMR3_CLK    PINMUX_ALTERNATE_FUNCTION_1

//  PORT_15_PIN_4
#define PORT_15_PIN_4_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0

//  PORT_15_PIN_5
#define PORT_15_PIN_5_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0

//  PORT_15_PIN_6
#define PORT_15_PIN_6_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0

//  PORT_15_PIN_7
#define PORT_15_PIN_7_AF_GPIO          PINMUX_ALTERNATE_FUNCTION_0

