/**
 ******************************************************************************
 * @file    ll_aton_rcompat.h
 * @author  SRA Artificial Intelligence & Embedded Architectures
 * @brief   Backward compatibility layer for RaSTa flow.
 *          Enables using ATON.h files generated by old regparser.
 *          Tested with N6 RTL.
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#ifndef __LL_ATON_COMPAT_H
#define __LL_ATON_COMPAT_H

/* STM32N6 compatibility layer */
#if defined(ATON_STM32N6) || defined(ATON_2CA)

#undef ATON_DEBUG_TRACE_CTRL_DT
#define ATON_DEBUG_TRACE_CTRL_DT(UNIT) UINT32_C(0x00000000)

#define ATON_BUSIF_CRYPT_NR_KEYS     2
#define ATON_BUSIF_0_KEY0_31_0_IDX   0
#define ATON_BUSIF_0_KEY0_31_0_S     0
#define ATON_BUSIF_0_KEY0_63_32_IDX  0
#define ATON_BUSIF_0_KEY0_63_32_S    1
#define ATON_BUSIF_0_KEY0_95_64_IDX  0
#define ATON_BUSIF_0_KEY0_95_64_S    2
#define ATON_BUSIF_0_KEY0_127_96_IDX 0
#define ATON_BUSIF_0_KEY0_127_96_S   3
#define ATON_BUSIF_0_KEY1_31_0_IDX   1
#define ATON_BUSIF_0_KEY1_31_0_S     0
#define ATON_BUSIF_0_KEY1_63_32_IDX  1
#define ATON_BUSIF_0_KEY1_63_32_S    1
#define ATON_BUSIF_0_KEY1_95_64_IDX  1
#define ATON_BUSIF_0_KEY1_95_64_S    2
#define ATON_BUSIF_0_KEY1_127_96_IDX 1
#define ATON_BUSIF_0_KEY1_127_96_S   3

#define ATON_STRENG_ENCRYPTION_EN(UNIT)    (((UNIT) < 10) ? UINT64_C(1) : 0)
#define ATON_BUSIF_ENCRYPTION_EN(UNIT)     (((UNIT) < 2) ? UINT64_C(1) : 0)
#define ATON_EPOCHCTRL_ENCRYPTION_EN(UNIT) (((UNIT) < 1) ? UINT64_C(1) : 0)

#define ATON_DEBUG_TRACE_ILINK_STATES_IDX_MAX(id) 1
#define ATON_DEBUG_TRACE_OLINK_STATES_IDX_MAX(id) 1

#define ATON_DEBUG_TRACE_ILINK_STATES_GET(unit, idx)                                                                   \
  (idx == 0 ? ATON_DEBUG_TRACE_LOW_ILINK_STATES_GET(unit) : ATON_DEBUG_TRACE_HIGH_ILINK_STATES_GET(unit))
#define ATON_DEBUG_TRACE_OLINK_STATES_GET(unit, idx)                                                                   \
  (idx == 0 ? ATON_DEBUG_TRACE_LOW_OLINK_STATES_GET(unit) : ATON_DEBUG_TRACE_HIGH_OLINK_STATES_GET(unit))

#endif // ATON_STM32N6 || ATON_2CA

#endif //__LL_ATON_COMPAT_H
