freeze ("$(MPY_LIB_DIR)/", "hts221.py")
freeze ("$(MPY_LIB_DIR)/", "lps22h.py")
freeze ("$(MPY_LIB_DIR)/", "lsm9ds1.py")
freeze ("$(MPY_LIB_DIR)/apds9960/", "apds9960")
freeze("$(PORT_DIR)/modules/scripts", "_mkfs.py")
