#!/bin/sh
if [ $# -ne 1 ]; then
    echo "usage `basename $0` device (STM32H743VI/STM32F765VI)"
    exit 1
fi

~/JLink_Linux_V656d_x86_64/JLinkGDBServer -if swd -halt -strict -cpu cortex-m -device $1
