name: '🔥 Firmware Build'

on:
  push:
    tags:
      - 'v*.*.*'
    branches:    
      - 'master'
    paths:
      - '**'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.json'
      - '!**.md'
      - '!**.rst'
      - '!**.md'
      - '!cubeai**'
      - '!scripts**'

  pull_request:
    branches:    
      - 'master'
    paths:
      - '**'
      - '.github/workflows/*.yml'
      - '.github/workflows/*.json'
      - '!**.md'
      - '!**.rst'
      - '!**.md'
      - '!cubeai**'
      - '!scripts**'

jobs:
  build-firmware:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target:
          - OPENMV2
          - OPENMV3
          - OPENMV4
          - OPENMV4P
          - OPENMVPT
          - OPENMV_RT1060
          - OPENMV_AE3
          - OPENMV_N6
          - ARDUINO_PORTENTA_H7
          - ARDUINO_GIGA
          - ARDUINO_NICLA_VISION
        qemu: [false]
        profile: [0]
        artifacts: [true]
        include:
          - target: DOCKER
            qemu: false
            profile: 0
            artifacts: false
          - target: OPENMV_N6
            qemu: false
            profile: 1
            artifacts: false
          - target: MPS2_AN500
            qemu: true
            profile: 0
            artifacts: false
          - target: MPS3_AN547
            qemu: true
            profile: 0
            artifacts: false
      fail-fast: false
    steps:
    - name: '⏳ Checkout repository'
      uses: actions/checkout@v6
      with:
        submodules: false

    - name: '🧱 Update submodules'
      run: source tools/ci.sh && ci_update_submodules

    - name: '♻ Cache SDK'
      uses: actions/cache@v5.0.3
      id: sdk-cache
      with:
        path: ~/openmv-sdk-1.0.0
        key: openmv-sdk-1.0.0-linux-x86_64

    - name: '🛠 Install dependencies'
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu-system-arm

    - name: '🛠 Install SDK'
      if: steps.sdk-cache.outputs.cache-hit != 'true'
      run: source tools/ci.sh && ci_install_sdk

    - name: '🏗 Build firmware'
      run: source tools/ci.sh && ci_build_target ${{ matrix.target }} ${{ matrix.qemu }} ${{ matrix.profile }} ${{ matrix.artifacts }}

    - name: '🧪 Run QEMU tests'
      if: matrix.qemu
      run: source tools/ci.sh && ci_run_qemu_tests ${{ matrix.target }}

    - name: '⬆ Upload artifacts'
      if: matrix.artifacts
      uses: actions/upload-artifact@v5
      with:
        name: ${{ matrix.target }}
        path: ${{ matrix.target }}
        if-no-files-found: error

  code-size-report:
    needs: build-firmware
    runs-on: ubuntu-24.04
    if: github.event_name == 'pull_request'
    steps:
    - name: '⏳ Checkout repository'
      uses: actions/checkout@v6
      with:
        submodules: false

    - name: '♻ Cache SDK'
      uses: actions/cache@v5.0.3
      id: sdk-cache
      with:
        path: ~/openmv-sdk-1.0.0
        key: openmv-sdk-1.0.0-linux-x86_64

    - name: '🛠 Install SDK'
      if: steps.sdk-cache.outputs.cache-hit != 'true'
      run: source tools/ci.sh && ci_install_sdk

    - name: '↓ Download artifacts'
      uses: actions/download-artifact@v6
      with:
        path: new_firmware
        merge-multiple: false

    - name: '↓ Download release'
      uses: robinraju/release-downloader@v1
      with:
        repository: 'openmv/openmv'
        tag: 'development'
        fileName: '*.zip'
        extract: false
        out-file-path: 'old_firmware'

    - name: '📝 Generate report'
      run: |
        SDK_DIR="${HOME}/openmv-sdk-1.0.0"
        export PATH="${SDK_DIR}/gcc/bin:${SDK_DIR}/python/bin:${PATH}"
        python3 tools/code_size.py > ${GITHUB_WORKSPACE}/${{ github.event.pull_request.number }}.md

    - name: '⬆ Upload report'
      uses: actions/upload-artifact@v5
      with:
        overwrite: true
        name: code-size-report
        path: ${{ github.event.pull_request.number }}.md
        if-no-files-found: error

  stable-release:
    needs: build-firmware
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: '⏳ Checkout repository'
      uses: actions/checkout@v6
      with:
        submodules: false

    - name: '↓ Download artifacts'
      uses: actions/download-artifact@v6
      with:
        path: firmware

    - name: '📦 Package firmware'
      run: source tools/ci.sh && ci_package_firmware_release ${{github.ref_name}}

    - name: "✏️ Generate release changelog"
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v6
      with:
        toTag: ${{ github.sha }}
        configuration: '.github/workflows/changelog.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: '🔥 Create stable release'
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
      with:
        draft: true
        files: firmware_*.zip
        body: ${{steps.changelog.outputs.changelog}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: '🧹 Remove artifacts'
      uses: geekyeggo/delete-artifact@v5
      with:
        name: firmware
        failOnError: false

  development-release:
    needs: build-firmware
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v') == false
    permissions:
      contents: write
    steps:
    - name: '⏳ Checkout repository'
      uses: actions/checkout@v6
      with:
        submodules: false

    - name: '↓ Download artifacts'
      uses: actions/download-artifact@v6
      with:
        path: firmware

    - name: '📦 Package firmware'
      run: source tools/ci.sh && ci_package_firmware_development

    - name: '🧹 Delete old release'
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        delete_release: true
        tag_name: development
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: "✏️ Generate release changelog"
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v6
      with:
        toTag: ${{ github.sha }}
        configuration: '.github/workflows/changelog.json'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: '🔥 Create development release'
      uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b
      with:
        draft: false
        name: Development Release
        tag_name: development
        body: |
            **⚠️ This is a development release, and it may be unstable.**
            ${{steps.changelog.outputs.changelog}}
        files: firmware/firmware_*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: '🧹 Remove artifacts'
      uses: geekyeggo/delete-artifact@v5
      with:
        name: firmware
        failOnError: false
